# Fusion Master Server
# Version 1

FROM      debian:wheezy

MAINTAINER      izissise <morisset.hugues@gmail.com>

EXPOSE 25255/udp


RUN apt-get update && apt-get install -y locales wget

RUN dpkg-reconfigure locales && \
    locale-gen C.UTF-8 && \
    /usr/sbin/update-locale LANG=C.UTF-8

ENV LC_ALL C.UTF-8




