// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef PROTOBUF_Protocol_2eproto__INCLUDED
#define PROTOBUF_Protocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Player.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Protocol_2eproto();
void protobuf_AssignDesc_Protocol_2eproto();
void protobuf_ShutdownFile_Protocol_2eproto();

class Protocol;

// ===================================================================

class Protocol : public ::google::protobuf::Message {
 public:
  Protocol();
  virtual ~Protocol();

  Protocol(const Protocol& from);

  inline Protocol& operator=(const Protocol& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Protocol& default_instance();

  void Swap(Protocol* other);

  // implements Message ----------------------------------------------

  Protocol* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Protocol& from);
  void MergeFrom(const Protocol& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 action = 1;
  inline bool has_action() const;
  inline void clear_action();
  static const int kActionFieldNumber = 1;
  inline ::google::protobuf::int32 action() const;
  inline void set_action(::google::protobuf::int32 value);

  // optional .Player player = 2;
  inline bool has_player() const;
  inline void clear_player();
  static const int kPlayerFieldNumber = 2;
  inline const ::Player& player() const;
  inline ::Player* mutable_player();
  inline ::Player* release_player();
  inline void set_allocated_player(::Player* player);

  // @@protoc_insertion_point(class_scope:Protocol)
 private:
  inline void set_has_action();
  inline void clear_has_action();
  inline void set_has_player();
  inline void clear_has_player();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::Player* player_;
  ::google::protobuf::int32 action_;
  friend void  protobuf_AddDesc_Protocol_2eproto();
  friend void protobuf_AssignDesc_Protocol_2eproto();
  friend void protobuf_ShutdownFile_Protocol_2eproto();

  void InitAsDefaultInstance();
  static Protocol* default_instance_;
};
// ===================================================================


// ===================================================================

// Protocol

// required int32 action = 1;
inline bool Protocol::has_action() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Protocol::set_has_action() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Protocol::clear_has_action() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Protocol::clear_action() {
  action_ = 0;
  clear_has_action();
}
inline ::google::protobuf::int32 Protocol::action() const {
  // @@protoc_insertion_point(field_get:Protocol.action)
  return action_;
}
inline void Protocol::set_action(::google::protobuf::int32 value) {
  set_has_action();
  action_ = value;
  // @@protoc_insertion_point(field_set:Protocol.action)
}

// optional .Player player = 2;
inline bool Protocol::has_player() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Protocol::set_has_player() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Protocol::clear_has_player() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Protocol::clear_player() {
  if (player_ != NULL) player_->::Player::Clear();
  clear_has_player();
}
inline const ::Player& Protocol::player() const {
  // @@protoc_insertion_point(field_get:Protocol.player)
  return player_ != NULL ? *player_ : *default_instance_->player_;
}
inline ::Player* Protocol::mutable_player() {
  set_has_player();
  if (player_ == NULL) player_ = new ::Player;
  // @@protoc_insertion_point(field_mutable:Protocol.player)
  return player_;
}
inline ::Player* Protocol::release_player() {
  clear_has_player();
  ::Player* temp = player_;
  player_ = NULL;
  return temp;
}
inline void Protocol::set_allocated_player(::Player* player) {
  delete player_;
  player_ = player;
  if (player) {
    set_has_player();
  } else {
    clear_has_player();
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.player)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Protocol_2eproto__INCLUDED
